### ISSUE TITLE
Ludus error while running on TurrisOS v4.x

### ISSUE THREAD

**Issue by ja-pa** [stratosphereips/Ludus#2]
Hi,
I tried to run Ludus on my Turris Omnia router (Turris OS v 4.x) but after while I get an error message (see below). I'm able to reproduce this issue quite reliably now.

I'm not sure what caused the error. I didn't use any special configuration for Suricata so maybe that caused the error. If you have any sample configuration I could try that.

my config file for Ludus /etc/ludus/ludus.config

```
[strategy]
filename=/usr/share/ludus/Strategizer/strategies/2017-07-18-defenseStrategyWith2HP-v1
[suricata]
allow=True
[output]
filename=/tmp/ludus_output.json
[settings]
router_ip = "192.168.1.1"
timeout=60
```

Error message:
```
Suricata is required for running Ludus. Starting Suricata with interface {} and default configuration.
Suricata is running
Ludus started on 2019-04-18 17:14:35.974898

Process Counter-1:1:
Traceback (most recent call last):
  File "/process.py", line 258, in _bootstrap
  File "/usr/share/ludus/Volumeter/volumeter.py", line 231, in run
    self.process_event(line)
  File "/usr/share/ludus/Volumeter/volumeter.py", line 134, in process_event
    dport = int(parts[8].strip("dport="))
ValueError: invalid literal for int() with base 10: 'src=147.229.xxx.xxx'
-------start: 2019-04-18 17:14:36.138427-------
```
cc @ondrej-lukas

**Comment by ondrej-lukas** [comment]
Thank for the report. Commit a969312c756ad6a99e164d9432b72724b0a1dbb3 has been tested on Turris Omnia after factory reset. Running install.py  creates the config files for both ludus and suricata and checks dependencies.
