### ISSUE TITLE
[feature request] suricata interface as command line option  

### ISSUE THREAD

**Issue by ja-pa** [stratosphereips/Ludus#3]
It would be nice if the interface for Suricata was passed as  ludus.py command line option since the wan interface has different eth numbers on different systems. (Turris 1.x, Turris Omnia, Turris Mox, etc. )
see 
https://github.com/stratosphereips/Ludus/blob/master/ludus.py#L331

**Comment by ondrej-lukas** [comment]
interfce option added to ludus. config file
