### ISSUE TITLE
500 Internal Server Error (TurrisOS 3.11.6)

### ISSUE THREAD

**Issue by ghost** [stratosphereips/Ludus#7]
Login into dashboard is possible and load of the CPUs is not too high – around 0.10 to 0.20
This is the message I get after logging into dashboard:

**Internal Server Error**
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Running jobs are:
`  751 root      201m S    {ludus.fcgi} /usr/bin/python3 /usr/share/ludus-gui/ludus.fcgi`
`32357 root     46816 S    {ludus.py} /usr/bin/python3 /usr/share/ludus/ludus.py -c /etc/ludus/ludus.config --pidfile /var/run/ludus`
`32363 root      219m S    {Suricata-Main} suricata -i eth1 -c /etc/ludus/suricata_for_ludus.yaml -l /var/log/ludus`

`/var/log/ludus/fast.log` shows the service is still running and collecting data.
`/etc/init.d/ludus restart` makes access to dashboard work again for some minutes. After a reboot of the router access to dashboard works for about 18 hours.

I am currently on Turris Omnia 1GB with TurrisOS 3.11.6 with 
`ludus_0.8-3_mvebu.ipk`and `ludus-gui_0.1-3_mvebu.ipk` installed.

sincere greetings from Vienna,

KreMic

**Comment by ondrej-lukas** [comment]
Hi KreMic, 

Thanks for reaching to us and for reporting the problem. We will look into it.

**Comment by ondrej-lukas** [comment]
Hi KreMic, 

the issue you mentioned will be fixed in the next release of the package. CZ.NIC is in charge of that, but it should happen shortly.
